# Generated by Django 3.2.8 on 2021-10-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_day', models.BooleanField()),
                ('weather_descriptions', models.CharField(max_length=60)),
                ('wind_dir', models.CharField(max_length=60)),
                ('feelslike', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('cloudcover', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('weather_code', models.IntegerField()),
                ('wind_degree', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='api.city')),
            ],
        ),
    ]
